apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: selinux-pac-payments-pr
spec:
  pipelineRef:
    name: selinux-pac-pr
  params:
    - name: manifest-path
      value: config/payments.manifest.example.yml
    - name: policy-dir
      value: selinux/payments
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
