apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: selinux-pac-myapp-pr
spec:
  pipelineRef:
    name: selinux-pac-pr
  params:
    - name: manifest-path
      value: config/myapp.manifest.yml
    - name: policy-dir
      value: selinux
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
