#!/usr/bin/env bash
#
# setup_rhel_hosts.sh — Two-box lab: RHEL dev + RHEL prod.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ANSIBLE_DIR="${PROJECT_ROOT}/ansible"

DEV_HOST=""
PROD_HOST=""
ANSIBLE_USER="${ANSIBLE_SSH_USER:-ansible}"
DEV_CHECKOUT=""
DEV_INVENTORY="${ANSIBLE_DIR}/inventory.dev.yml"
PROD_INVENTORY="${ANSIBLE_DIR}/inventory.production.yml"

usage() {
    cat <<EOF
Usage: $(basename "$0") <subcommand> [options]

Two RHEL boxes is the default lab: one **dev** (staging / AVC discovery) and
one **prod** (canary → soak → enforce). See docs/admin/RHEL_TWO_HOST.md.

Subcommands:
  write     Write ansible/inventory.dev.yml and inventory.production.yml
  ping      ansible ping both inventories
  doctor    getenforce / ausearch / sesearch on each host
  bootstrap Print SSH commands to install the reference app on the dev box

write options:
  --dev-host HOST     Dev box IP or DNS (required)
  --prod-host HOST    Prod box IP or DNS (required)
  --user NAME         SSH user (default: ansible, or ANSIBLE_SSH_USER)
  --dev-checkout PATH Repo on the DEV box (default: /home/<user>/selinux-pac)

Examples:
  bash scripts/setup_rhel_hosts.sh write --dev-host 10.0.0.10 --prod-host 10.0.0.20
  bash scripts/setup_rhel_hosts.sh ping
  bash scripts/setup_rhel_hosts.sh doctor
  bash scripts/setup_rhel_hosts.sh bootstrap
EOF
}

require_write_args() {
    if [[ -z "${DEV_HOST}" || -z "${PROD_HOST}" ]]; then
        echo "write requires --dev-host and --prod-host" >&2
        usage
        exit 2
    fi
}

write_inventories() {
    require_write_args
    local checkout="${DEV_CHECKOUT:-/home/${ANSIBLE_USER}/selinux-pac}"
    cat >"${DEV_INVENTORY}" <<EOF
# Generated by scripts/setup_rhel_hosts.sh — not for git.
# Dev RHEL: staging / policy discovery. soak_min_days=0 is lab-only.
#
# Controller-only (laptop / AAP): policy_artifact_dir, policy_pp_src.
# On rhel-dev after clone + setup_staging_env.sh: selinux_ops_dir, app_manifest_path.
# Do not point those two at playbook_dir — that is a Mac/AAP path.

all:
  hosts:
    rhel-dev:
      ansible_host: ${DEV_HOST}
      ansible_user: ${ANSIBLE_USER}
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: myapp
    domain: myapp_t
    install_root: /opt/myapp
    var_dir: /var/lib/myapp
    log_dir: /var/log/myapp
    runtime_dir: /run/myapp
    service_name: myapp.service
    selinux_ops_from_package: false
    selinux_ops_dir: ${checkout}/scripts
    policy_artifact_dir: "{{ playbook_dir }}/.."
    policy_pp_src: "{{ policy_artifact_dir }}/selinux/{{ app_name }}.pp"
    app_manifest_path: ${checkout}/config/myapp.manifest.yml
    ansible_env_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    soak_marker_file: "{{ var_dir }}/selinux_canary_deployed_at"
    soak_min_days: 0
    soak_max_avc: 0
    soak_max_net_new: 0
    soak_use_net_new: true
    selinux_pac_install_demo_units: false
    http_probe_host: "127.0.0.1"
EOF

    cat >"${PROD_INVENTORY}" <<EOF
# Generated by scripts/setup_rhel_hosts.sh — not for git.
# Prod RHEL: canary + production groups are the same host.

all:
  children:
    canary:
      hosts:
        rhel-prod:
    production:
      hosts:
        rhel-prod:
  hosts:
    rhel-prod:
      ansible_host: ${PROD_HOST}
      ansible_user: ${ANSIBLE_USER}
      ansible_become: true
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: myapp
    domain: myapp_t
    install_root: /opt/myapp
    var_dir: /var/lib/myapp
    log_dir: /var/log/myapp
    runtime_dir: /run/myapp
    service_name: myapp.service
    selinux_ops_from_package: true
    selinux_ops_dir: /usr/libexec/selinux-policy-ops
    app_manifest_path: /etc/myapp/selinux-manifest.yml
    policy_artifact_dir: "{{ playbook_dir }}/.."
    policy_pp_src: ""
    ansible_env_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    soak_marker_file: "{{ var_dir }}/selinux_canary_deployed_at"
    soak_min_days: 7
    soak_max_avc: 0
    soak_max_net_new: 0
    soak_use_net_new: true
    rollback_dnf_version: ""
    http_probe_host: "127.0.0.1"
EOF

    echo "Wrote ${DEV_INVENTORY} (dev=${DEV_HOST})"
    echo "Wrote ${PROD_INVENTORY} (prod=${PROD_HOST})"
    echo "NOTE: inventory.dev.yml has soak_min_days: 0 (lab only). Do not copy that onto prod."
    echo "Next: bash scripts/setup_rhel_hosts.sh ping"
}

require_inventories() {
    if [[ ! -f "${DEV_INVENTORY}" || ! -f "${PROD_INVENTORY}" ]]; then
        echo "Missing inventories. Run: bash scripts/setup_rhel_hosts.sh write --dev-host … --prod-host …" >&2
        exit 1
    fi
}

require_ansible() {
    if ! command -v ansible >/dev/null 2>&1; then
        echo "ansible not found on this controller. pip install ansible" >&2
        exit 1
    fi
}

ping_hosts() {
    require_inventories
    require_ansible
    echo "=== ping dev ==="
    ansible -i "${DEV_INVENTORY}" all -m ping
    echo "=== ping prod ==="
    ansible -i "${PROD_INVENTORY}" all -m ping
}

doctor_hosts() {
    require_inventories
    require_ansible
    echo "=== doctor dev ==="
    ansible -i "${DEV_INVENTORY}" all -b -m shell -a 'getenforce; command -v ausearch; command -v sesearch'
    echo "=== doctor prod ==="
    ansible -i "${PROD_INVENTORY}" all -b -m shell -a 'getenforce; command -v ausearch; command -v sesearch; rpm -q selinux-policy-ops'
}

print_bootstrap() {
    local dev_hint="rhel-dev.example.com"
    if [[ -f "${DEV_INVENTORY}" ]]; then
        dev_hint="$(awk '/ansible_host:/ { print $2; exit }' "${DEV_INVENTORY}" | tr -d '"')"
        [[ -n "${dev_hint}" ]] || dev_hint="rhel-dev.example.com"
    fi
    cat <<EOF
=== Bootstrap the DEV RHEL box (run over SSH as a user with sudo) ===
=== Next: docs/admin/RHEL_TWO_HOST.md Part 2 (look at the prompt: Mac vs rhel-dev) ===

ssh ${ANSIBLE_USER}@${dev_hint}
sudo dnf install -y git python3 policycoreutils policycoreutils-python-utils \\
  setools-console audit selinux-policy-devel
# Clone this repo on the box (or rsync from your laptop):
git clone https://github.com/anurag-saran/selinux-pac.git ~/selinux-pac
cd ~/selinux-pac
sudo bash scripts/setup_staging_env.sh --app-only
sudo bash scripts/write_domain_seed.sh --load
sudo bash scripts/selinux_pac_adopt.sh doctor

Generate on rhel-dev from AVCs, copy sources + .pp back, open a GitHub PR, then canary from the controller:
  ssh ${ANSIBLE_USER}@${dev_hint} 'cd ~/selinux-pac && sudo bash scripts/dev_generate_policy.sh --apply && bash scripts/compile_and_validate.sh selinux'
  scp ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/myapp.te ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/myapp.fc ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/policy_version.txt ${ANSIBLE_USER}@${dev_hint}:~/selinux-pac/selinux/myapp.pp selinux/
  bash scripts/demo_open_generated_pr.sh
  ansible-playbook -i ansible/inventory.dev.yml ansible/deploy_canary.yml

=== PROD RHEL box (no git clone) ===
=== Explained in docs/admin/RHEL_TWO_HOST.md Part 2g + Part 6 ===

# App first (scp app/ + setup_staging_env.sh --app-only). Then RPMs for policy.
sudo dnf install -y python3 python3-pip policycoreutils policycoreutils-python-utils setools-console audit
# After you build RPMs on the controller:
#   bash packaging/build_rpms.sh
# Install selinux-policy-ops + myapp-selinux from your internal repo, then:
  ansible-playbook -i ansible/inventory.production.yml ansible/deploy_canary.yml --limit canary
  ansible-playbook -i ansible/inventory.production.yml ansible/soak_monitor.yml --limit canary
# Customer prod waits 7 days. Talk-only: add -e force_enforce=true (still needs a ticket).
  ansible-playbook -i ansible/inventory.production.yml ansible/enforce_production.yml \\
    -e change_ticket=DEMO -e force_enforce=true

Docs: docs/admin/RHEL_TWO_HOST.md
EOF
}

parse_write_opts() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dev-host) DEV_HOST="$2"; shift 2 ;;
            --prod-host) PROD_HOST="$2"; shift 2 ;;
            --user) ANSIBLE_USER="$2"; shift 2 ;;
            --dev-checkout) DEV_CHECKOUT="$2"; shift 2 ;;
            -h|--help) usage; exit 0 ;;
            *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
        esac
    done
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

SUB="$1"
shift

case "${SUB}" in
    write) parse_write_opts "$@"; write_inventories ;;
    ping) ping_hosts ;;
    doctor) doctor_hosts ;;
    bootstrap) print_bootstrap ;;
    -h|--help) usage ;;
    *) echo "Unknown subcommand: ${SUB}" >&2; usage; exit 2 ;;
esac
