all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_become: true
  vars:
    app_name: myapp
    domain: myapp_t
    install_root: /opt/myapp
    var_dir: /var/lib/myapp
    runtime_dir: /run/myapp
    service_name: myapp.service
    policy_pp_path: "{{ playbook_dir }}/../selinux/myapp.pp"
    project_root: "{{ playbook_dir }}/.."
    app_manifest_path: "{{ project_root }}/config/{{ app_name }}.manifest.yml"
    ansible_env_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
